name: savoniq
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  direct_link: ^0.2.2
  flutter_file_downloader: ^1.2.1
  simple_progress_indicators: ^0.2.0
  get_storage: ^2.1.1
  share_plus: ^7.2.1
  rive: ^0.9.1
  flutter_spinkit: ^5.2.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  dio: ^5.4.1


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/Apppnglogo.png"
  min_sdk_android: 23
  remove_alpha_ios: true

flutter: 
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Fontspring-DEMO-visbycf
      fonts:
        - asset: assets\fonts\Fontspring-DEMO-visbycf-bold.ttf
        - asset: assets\fonts\Fontspring-DEMO-visbycf-extrabold.ttf
        - asset: assets\fonts\Fontspring-DEMO-visbycf-regular.ttf

